//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canada2DCode.DataBaseEngine
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Canada2DCodeEntities : DbContext
    {
        public Canada2DCodeEntities()
            : base("name=Canada2DCodeEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Contacts> Contacts { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<State> State { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UploadedFiles> UploadedFiles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Addresses> Addresses { get; set; }
        public virtual DbSet<CustomerEmail> CustomerEmail { get; set; }
        public virtual DbSet<CustomerPhone> CustomerPhone { get; set; }
        public virtual DbSet<Object2DCode> Object2DCode { get; set; }
        public virtual DbSet<Organization> Organization { get; set; }
        public virtual DbSet<Production_Categories> Production_Categories { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<User_Roles> User_Roles { get; set; }
        public virtual DbSet<ObjectEvent> ObjectEvent { get; set; }
        public virtual DbSet<ObjectPerson> ObjectPerson { get; set; }
        public virtual DbSet<ObjectProduction> ObjectProduction { get; set; }
        public virtual DbSet<ObjectTbl> ObjectTbl { get; set; }
    }
}
