//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canada2DCode.DataBaseEngine
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerPhone
    {
        public int CustomerPhoneID { get; set; }
        public string CustomerPhone1 { get; set; }
        public Nullable<int> CustomeID { get; set; }
        public Nullable<bool> IsinActive { get; set; }
        public Nullable<int> QueueCode { get; set; }
    }
}
