//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canada2DCode.DataBaseEngine
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjectTbl
    {
        public int Object_id { get; set; }
        public string Object_name { get; set; }
        public int Category_id { get; set; }
        public short Model_year { get; set; }
        public Nullable<int> OrganizationID_FK { get; set; }
        public string C2DMACode { get; set; }
        public byte[] QRCode { get; set; }
        public string ContentsURL { get; set; }
        public byte[] PrivateKey { get; set; }
        public Nullable<int> OpenToRole { get; set; }
        public Nullable<System.Guid> BlockID { get; set; }
        public Nullable<System.Guid> NextChainID { get; set; }
        public Nullable<System.DateTime> CreatedDate_DT { get; set; }
        public string CreatedBy_NV { get; set; }
        public Nullable<System.DateTime> DeleteDate_DT { get; set; }
        public string DeleteByName_NV { get; set; }
    }
}
