//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canada2DCode.DataBaseEngine
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjectPerson
    {
        public int PersonID_PK { get; set; }
        public Nullable<int> ObjectID_FK { get; set; }
        public string Person_Name { get; set; }
        public string PersonType { get; set; }
        public string Description { get; set; }
        public string Gender { get; set; }
        public string Title { get; set; }
        public string Telephone { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Position { get; set; }
        public string Email { get; set; }
        public Nullable<int> AddID_FK { get; set; }
        public string C2DCodeType { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Deleted_Date { get; set; }
        public string PersonDetailsUrl { get; set; }
    }
}
