//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canada2DCode.DataBaseEngine
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjectProduction
    {
        public int Product_id { get; set; }
        public int ObjectID_FK { get; set; }
        public string Product_name { get; set; }
        public int Brand_id { get; set; }
        public int Category_id { get; set; }
        public string Model { get; set; }
        public short Model_year { get; set; }
        public decimal List_price { get; set; }
        public string ItemUnit { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string Manufacturer_vendor { get; set; }
        public Nullable<System.DateTime> Manufacture_Date { get; set; }
        public string Shipped_From { get; set; }
        public string Shipped_To { get; set; }
        public Nullable<System.DateTime> Shipped_Date { get; set; }
        public Nullable<int> OrganizationID_FK { get; set; }
        public string C2DMACode { get; set; }
        public byte[] QRCode { get; set; }
        public string ContentsURL { get; set; }
        public byte[] PrivateKey { get; set; }
        public Nullable<int> OpenToRole { get; set; }
        public Nullable<System.Guid> BlockID { get; set; }
        public Nullable<System.Guid> NextChainID { get; set; }
        public Nullable<System.DateTime> CreatedDate_DT { get; set; }
        public string CreatedBy_NV { get; set; }
        public Nullable<System.DateTime> DeleteDate_DT { get; set; }
        public string DeleteByName_NV { get; set; }
    }
}
