//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canada2DCode.DataBaseEngine
{
    using System;
    using System.Collections.Generic;
    
    public partial class Object2DCode
    {
        public int Objec2DCodeIDPK { get; set; }
        public Nullable<int> Object_id_FK { get; set; }
        public Nullable<int> C2DCodeID { get; set; }
        public Nullable<int> C2DCodeType { get; set; }
        public byte[] C2DCodeContents { get; set; }
        public string IsInActive { get; set; }
        public Nullable<System.Guid> BlockID_FK { get; set; }
    }
}
