//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canada2DCode.DataBaseEngine
{
    using System;
    using System.Collections.Generic;
    
    public partial class Production_Categories
    {
        public int Category_id { get; set; }
        public string Category_name { get; set; }
        public Nullable<int> AdminLevel { get; set; }
        public Nullable<bool> IsInActive { get; set; }
    }
}
