//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canada2DCode.DataBaseEngine
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        public int RoleID_PK { get; set; }
        public string RoleName { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> IsInactive { get; set; }
    }
}
