//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canada2DCode.DataBaseEngine
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int UserID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string EmailID { get; set; }
        public string Gender { get; set; }
        public byte[] PasswordHash { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName_CN { get; set; }
        public Nullable<bool> UserIsComfirmed { get; set; }
        public Nullable<int> OrganizationID_FK { get; set; }
        public Nullable<System.DateTime> CreateDate_DT { get; set; }
        public string CreatedBy_NV { get; set; }
        public Nullable<System.DateTime> DeleteDate_DT { get; set; }
        public string DeleteBy_NV { get; set; }
        public Nullable<System.DateTime> ExpiredDate_DT { get; set; }
    }
}
