//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canada2DCode.DataBaseEngine
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Roles
    {
        public int UserRoleID_PK { get; set; }
        public int UserID_FK { get; set; }
        public int RoleID_FK { get; set; }
        public Nullable<System.DateTime> Created_DT { get; set; }
        public string CreatedBy_NV { get; set; }
        public Nullable<System.DateTime> Delete_DT { get; set; }
        public string DeleteBy_NV { get; set; }
    }
}
